/** ADD */
// export const ADD_REQUEST = 'ADD_REQUEST';
// export const ADD_SUCCESS = 'ADD_SUCCESS';
// export const ADD_FAILURE = 'ADD_FAILURE';

// /** REMOVE */
// export const REMOVE_REQUEST = 'REMOVE_REQUEST';
// export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';
// export const REMOVE_FAILURE = 'REMOVE_FAILURE';

export enum ActionTypes {
  ADD_REQUEST = 'ADD_REQUEST',
  ADD_SUCCESS = 'ADD_SUCCESS',
  ADD_FAILURE = 'ADD_FAILURE',
  REMOVE_REQUEST = 'REMOVE_FAILURE',
  REMOVE_SUCCESS = 'REMOVE_SUCCESS',
  REMOVE_FAILURE = 'REMOVE_FAILURE'
}
